### ISSUE TITLE
IOS problem

### ISSUE THREAD

**Issue by lecicdjuro** [MEnigma/flutter_rtmp#1]
There is a issue on IOS devices.
Widget is continuously refreshing and blinking.
I tried IOS 12 and 13

**Comment by MEnigma** [comment]
> There is a issue on IOS devices.
> Widget is continuously refreshing and blinking.
> I tried IOS 12 and 13

probable a timer in your widget, U can solve this issue in following methods:
1. release version [v0.1.3](https://github.com/MEnigma/flutter_rtmp/releases/tag/v0.1.3) has solve the problem

2. you can try to set 
```
        RtmpView(
            checkPermission=false,
            manager=_rtmpManager??=RtmpManager()
        )
```
3. insert RtmpView into a custom Stateless/Statefull widget 
```
class CustomRtmpWidget extends StatelessWidget {
  final String rtmpUrl;
  final RtmpManager manager;
  CustomWidget({@required this.rtmpUrl, @required this.manager});

  @override
  Widget build(BuildContext context) => RtmpView(
        manager: manager,
      );
}

```
