### ISSUE TITLE
ios info.plist 需要通迅录等多个权限，是本插件需要还是 LFLiveKit?

### ISSUE THREAD

**Issue by figbin** [MEnigma/flutter_rtmp#11]
发布到苹果提示需要如下权限：
NSContactsUsageDescription
NSCalendarsUsageDescription
NSAppleMusicUsageDescription
NSMotionUsageDescription
NSSpeechRecognitionUsageDescription
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription

请问为什么推流需要这么多权限，是必须的吗

**Comment by MEnigma** [comment]
> 发布到苹果提示需要如下权限：
> NSContactsUsageDescription
> NSCalendarsUsageDescription
> NSAppleMusicUsageDescription
> NSMotionUsageDescription
> NSSpeechRecognitionUsageDescription
> NSLocationAlwaysUsageDescription
> NSLocationWhenInUseUsageDescription
> 
> 请问为什么推流需要这么多权限，是必须的吗

插件只需要相机/麦克风权限
建议跟踪一下权限来源

在tag0.1.6之后的版本不进行权限管理,在tag0.1.6.1中移除了'permission_handler'插件

感谢更正

**Comment by figbin** [comment]
确实是这个问题，刚刚找到了问题
https://github.com/Baseflow/flutter-permission-handler/issues/26
之前用的是您的低版本没太注意permission_handler。
谢谢作者！
