### ISSUE TITLE
再提个问题 iOS 竖屏时 镜头默认是横屏。rotate正好相反

### ISSUE THREAD

**Issue by figbin** [MEnigma/flutter_rtmp#12]
默认旋转了摄像头，相当奇怪，不懂怎么描述。
有看到 RtmpConfig 但注释为默认未启用。
作者能不能有时间检查一下。这样直播无法用啊。

**Comment by MEnigma** [comment]
> 默认旋转了摄像头，相当奇怪，不懂怎么描述。
> 有看到 RtmpConfig 但注释为默认未启用。
> 作者能不能有时间检查一下。这样直播无法用啊。

感谢指出
修改已提交
v0.1.6.1 重新指向 commit (5b99f69e4b766d3615a4bc4b2d3d04d66fff74cf)

**Comment by figbin** [comment]
证实可用，效果很好。
感谢作者高效工作！
