### ISSUE TITLE
IOS 真机未开始直播时切换摄像头闪退。

### ISSUE THREAD

**Issue by figbin** [MEnigma/flutter_rtmp#9]
这个和 #2 应该是一样的，能不能检查下呢。

**Comment by MEnigma** [comment]
已经修复, commit : 29e7233120d4374b8de1551a70669fd532db0f84
覆盖如下配置即可
  flutter_rtmp:
    git:
      url: https://github.com/MEnigma/flutter_rtmp.git 
      ref: 29e7233120d4374b8de1551a70669fd532db0f84

**Comment by figbin** [comment]
证实可用。感谢作者！
